language: php

matrix:
  fast_finish: true

  include:
    - php: 5.5
      env: TYPO3_VERSION=^7.6
    - php: 5.5
      env: TYPO3_VERSION=dev-master
    - php: 5.6
      env: TYPO3_VERSION=^7.6 CODECEPTION_TESTS=yes
    - php: 5.6
      env: TYPO3_VERSION=dev-master
    - php: 7
      env: TYPO3_VERSION=^7.6
    - php: 7
      env: TYPO3_VERSION=dev-master

env:
  global:
    - secure: "cC0vyE6OZPBSUCQAPs82psy5NSTRpzUO7lzAnv15MIAgWXbCKrXKR0tAjPdosSZg3JM0Yo9j5PI5Wkt8P/LMZcsVrTFcCKBpbK6U3soXeTg2nhPgtgowzkld4NuL81BfnvbY7dJXr3EKXAxgKmUjLN6FqbNs6DVa2SRBLglBn5I="

sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer --version
  - if [ "$GITHUB_COMPOSER_AUTH" ]; then composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH; fi

before_script:
  - phpenv config-rm xdebug.ini
  - composer require typo3/cms=$TYPO3_VERSION
  # We currently need to get rid of the typo3/cms requirement in composer.json
  - git reset --hard HEAD
  - export TYPO3_PATH_WEB=$PWD/.Build/Web

script:
  - >
    echo;
    echo "Running unit tests";
    .Build/bin/phpunit -c .Build/vendor/typo3/cms/typo3/sysext/core/Build/UnitTests.xml Tests/Unit/
  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
  - >
    if [[ "$CODECEPTION_TESTS" == "yes" ]]; then
        echo;
        echo "Starting framebuffer"
        sh -e /etc/init.d/xvfb start
        export DISPLAY=:99.0
        echo "Starting selenium server"
        wget http://selenium-release.storage.googleapis.com/2.48/selenium-server-standalone-2.48.2.jar
        java -jar selenium-server-standalone-2.48.2.jar > /dev/null 2>&1 &
        echo "Waiting for servers to start..."
        sleep 5
        echo "Running codeception tests";
        .Build/bin/codecept run --env stable --env master
    fi